title: <p align="center"> Dona Inayyah </p>

logo: "images/picture-modified.png"

description:
  <p align="center">
  <a href="pdf/Inayyah_Resume2023.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/dona-inayyah/">LinkedIn</a> |
  <a href="https://github.com/inayyah-d">GitHub</a>
  </p>
  
  <p align="justify">
  - B.S. in Applied Mathematics, Emphasis in Data Science
  <br><br>
  - Junior
  <br><br>
  - San Francisco State University
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

